using Ecosys.Shared.Contracts.Integration;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Ecosys.Infrastructure.Integrations;

internal sealed class QuestPdfRenderer : IPdfRenderer
{
    public byte[] RenderWorkOrderReportPdf(string title, IReadOnlyCollection<string> sections)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
            container.Page(page =>
            {
                page.Margin(32);
                page.Header().Text(title).FontSize(20).SemiBold();
                page.Content().Column(column =>
                {
                    foreach (var section in sections)
                    {
                        column.Item().PaddingVertical(4).Text(section);
                    }
                });
                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Ecosys");
                });
            }))
            .GeneratePdf();
    }
}
